const encoder = new TextEncoder();
async function hash(value){const bytes=await crypto.subtle.digest('SHA-256',encoder.encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function cookie(request){return request.headers.get('Cookie')?.match(/controle_session=([^;]+)/)?.[1]}
export default {async fetch(request,env){const url=new URL(request.url);const row=await env.DB.prepare('SELECT data FROM settings WHERE id=2').first();const stored=row?.data||await hash('123');if(!row)await env.DB.prepare('INSERT INTO settings (id,data) VALUES (2,?)').bind(stored).run();
 if(url.pathname==='/api/login'&&request.method==='POST'){const {password}=await request.json();if(await hash(password)!==stored)return new Response('Unauthorized',{status:401});return new Response('ok',{headers:{'Set-Cookie':`controle_session=${stored}; HttpOnly; Secure; SameSite=Strict; Max-Age=86400`}})}
 if(url.pathname==='/api/session'&&request.method==='GET'){return cookie(request)===stored?new Response('ok'):new Response('Unauthorized',{status:401})}
 if(url.pathname==='/api/password'&&request.method==='PUT'){if(cookie(request)!==stored)return new Response('Unauthorized',{status:401});const {oldPassword,newPassword}=await request.json();if(await hash(oldPassword)!==stored||!newPassword)return new Response('Invalid',{status:400});const next=await hash(newPassword);await env.DB.prepare('UPDATE settings SET data=? WHERE id=2').bind(next).run();return new Response('ok')}
 if(url.pathname==='/api/items'||url.pathname==='/api/expenses'){if(cookie(request)!==stored)return new Response('Unauthorized',{status:401});const id=url.pathname==='/api/items'?1:3;if(request.method==='GET'){const data=await env.DB.prepare('SELECT data FROM settings WHERE id=?').bind(id).first();return Response.json(data?JSON.parse(data.data):[])}if(request.method==='PUT'){await env.DB.prepare('INSERT INTO settings (id,data) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(id,JSON.stringify(await request.json())).run();return Response.json({ok:true})}}
 return env.ASSETS.fetch(request)}};
